title: Oakland Finish Up Weekend
tagline: Be Amazed. Be Amazing.
url: http://oaklandfinishup.com

timezone: US/Pacific

collections:
  - sections

exclude: [bower_components,node_modules,javascripts,stylesheets,README*,params.json]

google-analytics: UA-61672521-1

plugins:
  - jekyll-sitemap
