title: Oakland Finish Up Weekend
tagline: Be Amazed. Be Amazing. Finish Up.
description: Get guidance, mentorship and inspiration at Finish Up Weekend in Oakland's beautiful Port Workspaces.
url: https://oaklandfinishup.com
author: Seemant Kulleen
email: seemantk@gmail.com

timezone: US/Pacific

collections:
  - sections

collections_dir: collections

exclude: [bower_components,node_modules,javascripts,stylesheets,README*,params.json]

google-analytics: UA-61672521-1

plugins:
  - jekyll-sitemap
